export type ProfileType = {
  id: string;
  profileId: string;
  LastName: string;
  FirstName: string;
  OtherNames?: string;
  BVN: string;
  PhoneNo: string;
  alternatePhoneNo?: string;
  Gender: string;
  DateOfBirth: string;
  Address: string;
  NationalIdentityNo: string;
  NextOfKinPhoneNo: string;
  NextOfKinName: string;
  ReferralPhoneNo: string;
  ReferralName: string;
  Email: string;
  CustomerImage: string;
  loanAgreement: string;
  organizationEmployer: string;
  ippisNumber: string;
  loanTenor: string;
  loanAmount: string;
  createdAt: string;
  updatedAt: string;
  state: string;
  CustomerSignature?: string;
  IdentificationImage?: string;
  otherDocuments?: {title: string, otherDocument: string}[];
  title: string;
  workIdentification: string;
  salaryAccountNumber: string;
  bankName: string;
};
